/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import model.*;
import controller.*;
import java.io.FileInputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import javax.swing.JOptionPane;

/**
 *
 * @author crist
 */
public final class Main extends javax.swing.JFrame {

    private BaseDeDados baseDeDados;
    public final UserRegister userRegister = new UserRegister();
    public final ScreenClient screenClient;
    public final ScreenAgency screenAgency;
    public final ScreenVehicle screenVehicle;
    public final ScreenLocate screenLocate;
    public final ScreenPayment screenPayment;

    private static final String USER_FILE = "users.dat";

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        exibirMenu(false);
        baseDeDados = new BaseDeDados();
        screenClient = new ScreenClient(baseDeDados);
        screenVehicle = new ScreenVehicle(baseDeDados);
        screenLocate = new ScreenLocate(baseDeDados);
        screenAgency = new ScreenAgency(baseDeDados);
        screenPayment = new ScreenPayment(baseDeDados);
        btnSair.setEnabled(false);

    }

    public void exibirMenu(boolean valor) {
        menuBar.setVisible(valor);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        desktop = new javax.swing.JDesktopPane();
        painelInicial = new javax.swing.JPanel();
        labelUserName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        inputUsuario = new javax.swing.JTextField();
        inputSenha = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        btnCadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        labelAvisos = new javax.swing.JLabel();
        btnSair = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuClientes = new javax.swing.JMenu();
        linkClientes = new javax.swing.JMenuItem();
        menuVeiculos = new javax.swing.JMenu();
        linkVeiculos = new javax.swing.JMenuItem();
        menuAgencias = new javax.swing.JMenu();
        linkAgencias = new javax.swing.JMenuItem();
        menuAlugueis = new javax.swing.JMenu();
        linkAlugeis = new javax.swing.JMenuItem();
        menuPagamentos = new javax.swing.JMenu();
        linkPagamentos = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CPR - Veículos Automotores");
        setMinimumSize(new java.awt.Dimension(1080, 580));
        setResizable(false);

        desktop.setPreferredSize(new java.awt.Dimension(1280, 720));

        painelInicial.setBackground(new java.awt.Color(18, 20, 31));
        painelInicial.setMaximumSize(new java.awt.Dimension(1280, 720));
        painelInicial.setMinimumSize(new java.awt.Dimension(1280, 720));
        painelInicial.setPreferredSize(new java.awt.Dimension(1280, 720));

        labelUserName.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        labelUserName.setForeground(new java.awt.Color(218, 31, 79));
        labelUserName.setText(" ");
        labelUserName.setPreferredSize(new java.awt.Dimension(100, 35));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/svg.png"))); // NOI18N

        inputUsuario.setBackground(new java.awt.Color(9, 13, 25));
        inputUsuario.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        inputUsuario.setForeground(new java.awt.Color(218, 31, 79));
        inputUsuario.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputUsuario.setBorder(null);
        inputUsuario.setPreferredSize(new java.awt.Dimension(220, 50));
        inputUsuario.setSelectedTextColor(new java.awt.Color(18, 20, 31));
        inputUsuario.setSelectionColor(new java.awt.Color(218, 31, 79));

        inputSenha.setBackground(new java.awt.Color(9, 13, 25));
        inputSenha.setFont(new java.awt.Font("Roboto Black", 0, 18)); // NOI18N
        inputSenha.setForeground(new java.awt.Color(218, 31, 79));
        inputSenha.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        inputSenha.setBorder(null);
        inputSenha.setPreferredSize(new java.awt.Dimension(220, 50));
        inputSenha.setSelectedTextColor(new java.awt.Color(18, 20, 31));
        inputSenha.setSelectionColor(new java.awt.Color(218, 31, 79));

        jLabel2.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Usuário");

        jLabel4.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 102, 102));
        jLabel4.setText("Senha");

        btnEntrar.setBackground(new java.awt.Color(218, 30, 78));
        btnEntrar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnEntrar.setForeground(new java.awt.Color(9, 13, 25));
        btnEntrar.setText("ENTRAR");
        btnEntrar.setBorder(null);
        btnEntrar.setBorderPainted(false);
        btnEntrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEntrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEntrar.setMaximumSize(new java.awt.Dimension(110, 45));
        btnEntrar.setMinimumSize(new java.awt.Dimension(110, 45));
        btnEntrar.setPreferredSize(new java.awt.Dimension(110, 45));
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Não possui conta?");

        btnCadastrar.setBackground(new java.awt.Color(9, 13, 25));
        btnCadastrar.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnCadastrar.setForeground(new java.awt.Color(218, 31, 79));
        btnCadastrar.setText("CADASTRE-SE");
        btnCadastrar.setBorder(null);
        btnCadastrar.setBorderPainted(false);
        btnCadastrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCadastrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnCadastrar.setMaximumSize(new java.awt.Dimension(110, 45));
        btnCadastrar.setMinimumSize(new java.awt.Dimension(110, 45));
        btnCadastrar.setPreferredSize(new java.awt.Dimension(110, 45));
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Black White and Red Modern Automotive Logo.png"))); // NOI18N

        labelAvisos.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        labelAvisos.setForeground(new java.awt.Color(218, 31, 79));
        labelAvisos.setText(" ");

        btnSair.setBackground(new java.awt.Color(218, 30, 78));
        btnSair.setFont(new java.awt.Font("Roboto Black", 0, 14)); // NOI18N
        btnSair.setForeground(new java.awt.Color(9, 13, 25));
        btnSair.setText("SAIR");
        btnSair.setBorder(null);
        btnSair.setBorderPainted(false);
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSair.setMaximumSize(new java.awt.Dimension(110, 45));
        btnSair.setMinimumSize(new java.awt.Dimension(110, 45));
        btnSair.setPreferredSize(new java.awt.Dimension(110, 45));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Roboto Black", 0, 48)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(218, 31, 79));
        jLabel8.setText("LOGIN");

        javax.swing.GroupLayout painelInicialLayout = new javax.swing.GroupLayout(painelInicial);
        painelInicial.setLayout(painelInicialLayout);
        painelInicialLayout.setHorizontalGroup(
            painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicialLayout.createSequentialGroup()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(painelInicialLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(364, 364, 364)
                .addGroup(painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInicialLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(painelInicialLayout.createSequentialGroup()
                        .addGroup(painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2)
                            .addComponent(inputSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(painelInicialLayout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jLabel8)))
                        .addGroup(painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(painelInicialLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(labelAvisos, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, painelInicialLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))))))
        );
        painelInicialLayout.setVerticalGroup(
            painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(painelInicialLayout.createSequentialGroup()
                .addGroup(painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(painelInicialLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(painelInicialLayout.createSequentialGroup()
                                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(14, 14, 14)
                                .addComponent(labelUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(painelInicialLayout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2)))
                        .addGap(301, 301, 301))
                    .addGroup(painelInicialLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(painelInicialLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(inputSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAvisos))
                        .addGap(18, 18, 18)
                        .addComponent(btnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        desktop.setLayer(painelInicial, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout desktopLayout = new javax.swing.GroupLayout(desktop);
        desktop.setLayout(desktopLayout);
        desktopLayout.setHorizontalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        desktopLayout.setVerticalGroup(
            desktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(painelInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        menuBar.setBackground(new java.awt.Color(18, 20, 31));
        menuBar.setBorder(null);
        menuBar.setOpaque(true);
        menuBar.setPreferredSize(new java.awt.Dimension(72, 40));

        menuClientes.setBackground(new java.awt.Color(18, 20, 31));
        menuClientes.setBorder(null);
        menuClientes.setForeground(new java.awt.Color(102, 102, 102));
        menuClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users-three.png"))); // NOI18N
        menuClientes.setText("CLIENTES");
        menuClientes.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        menuClientes.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuClientes.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        menuClientes.setMargin(new java.awt.Insets(0, 11, 3, 11));
        menuClientes.setMinimumSize(new java.awt.Dimension(255, 16));
        menuClientes.setPreferredSize(new java.awt.Dimension(255, 16));
        menuClientes.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/users-three.png"))); // NOI18N

        linkClientes.setText("ACESSAR MENU");
        linkClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkClientesActionPerformed(evt);
            }
        });
        menuClientes.add(linkClientes);

        menuBar.add(menuClientes);

        menuVeiculos.setBackground(new java.awt.Color(18, 20, 31));
        menuVeiculos.setBorder(null);
        menuVeiculos.setForeground(new java.awt.Color(102, 102, 102));
        menuVeiculos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/motorcycle.png"))); // NOI18N
        menuVeiculos.setText("VEÍCULOS");
        menuVeiculos.setFont(new java.awt.Font("Raleway Black", 0, 12)); // NOI18N
        menuVeiculos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuVeiculos.setMinimumSize(new java.awt.Dimension(250, 16));
        menuVeiculos.setPreferredSize(new java.awt.Dimension(255, 22));

        linkVeiculos.setText("ACESSAR MENU");
        linkVeiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkVeiculosActionPerformed(evt);
            }
        });
        menuVeiculos.add(linkVeiculos);

        menuBar.add(menuVeiculos);

        menuAgencias.setBackground(new java.awt.Color(18, 20, 31));
        menuAgencias.setBorder(null);
        menuAgencias.setForeground(new java.awt.Color(102, 102, 102));
        menuAgencias.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/bank.png"))); // NOI18N
        menuAgencias.setText("AGÊNCIAS");
        menuAgencias.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        menuAgencias.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuAgencias.setPreferredSize(new java.awt.Dimension(255, 22));

        linkAgencias.setText("ACESSAR MENU");
        linkAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkAgenciasActionPerformed(evt);
            }
        });
        menuAgencias.add(linkAgencias);

        menuBar.add(menuAgencias);

        menuAlugueis.setBackground(new java.awt.Color(18, 20, 31));
        menuAlugueis.setBorder(null);
        menuAlugueis.setForeground(new java.awt.Color(102, 102, 102));
        menuAlugueis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/tag.png"))); // NOI18N
        menuAlugueis.setText("ALUGUÉIS");
        menuAlugueis.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        menuAlugueis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuAlugueis.setPreferredSize(new java.awt.Dimension(255, 22));

        linkAlugeis.setText("ACESSAR MENU");
        linkAlugeis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkAlugeisActionPerformed(evt);
            }
        });
        menuAlugueis.add(linkAlugeis);

        menuBar.add(menuAlugueis);

        menuPagamentos.setBackground(new java.awt.Color(18, 20, 31));
        menuPagamentos.setBorder(null);
        menuPagamentos.setForeground(new java.awt.Color(102, 102, 102));
        menuPagamentos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/hand-coins.png"))); // NOI18N
        menuPagamentos.setText("PAGAMENTOS");
        menuPagamentos.setFont(new java.awt.Font("Roboto Black", 0, 12)); // NOI18N
        menuPagamentos.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        menuPagamentos.setPreferredSize(new java.awt.Dimension(259, 22));

        linkPagamentos.setText("ACESSAR MENU");
        linkPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                linkPagamentosActionPerformed(evt);
            }
        });
        menuPagamentos.add(linkPagamentos);

        menuBar.add(menuPagamentos);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(desktop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktop, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed

        String username = inputUsuario.getText().trim();
        String password = new String(inputSenha.getPassword());
        User user = loadUser(username);
        if (user != null && user.authenticate(password)) {
            JOptionPane.showMessageDialog(this, "Bem vindo " + user.getUsername() + "!", "Acesso permitido", JOptionPane.INFORMATION_MESSAGE);
            exibirMenu(true);
            inputUsuario.setText("");
            inputUsuario.setEditable(false);
            inputSenha.setText("");
            inputSenha.setEditable(false);
            labelAvisos.setText("");
            btnSair.setEnabled(true);
            btnEntrar.setEnabled(false);
            btnCadastrar.setEnabled(false);
            labelUserName.setText(username);
        } else {
            inputSenha.setText("");
            labelAvisos.setText("Usuário ou senha inválido!");
        }


    }//GEN-LAST:event_btnEntrarActionPerformed

    private void linkClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkClientesActionPerformed
        desktop.add(screenClient);
        screenClient.setVisible(true);
    }//GEN-LAST:event_linkClientesActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        desktop.add(userRegister);
        userRegister.setVisible(true);
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void linkAlugeisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkAlugeisActionPerformed
        desktop.add(screenLocate);
        screenLocate.setVisible(true);
    }//GEN-LAST:event_linkAlugeisActionPerformed

    private void linkAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkAgenciasActionPerformed
        desktop.add(screenAgency);
        screenAgency.setVisible(true);
    }//GEN-LAST:event_linkAgenciasActionPerformed

    private void linkVeiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkVeiculosActionPerformed
        desktop.add(screenVehicle);
        screenVehicle.setVisible(true);
    }//GEN-LAST:event_linkVeiculosActionPerformed

    private void linkPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_linkPagamentosActionPerformed
        desktop.add(screenPayment);
        screenPayment.setVisible(true);
    }//GEN-LAST:event_linkPagamentosActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        btnSair.setEnabled(false);
        labelUserName.setText("");
        menuBar.setVisible(false);
        inputUsuario.setEditable(true);
        inputUsuario.requestFocus();

        inputSenha.setEditable(true);
        btnEntrar.setEnabled(true);
        btnCadastrar.setEnabled(true);

    }//GEN-LAST:event_btnSairActionPerformed

    private User loadUser(String username) {
        try (ObjectInputStream ois = new ObjectInputStream(new FileInputStream(USER_FILE))) {
            User user = (User) ois.readObject();
            if (user.getUsername().equals(username)) {
                return user;
            }
        } catch (IOException | ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        return null;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnSair;
    private javax.swing.JDesktopPane desktop;
    private javax.swing.JPasswordField inputSenha;
    private javax.swing.JTextField inputUsuario;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JLabel labelAvisos;
    private javax.swing.JLabel labelUserName;
    private javax.swing.JMenuItem linkAgencias;
    private javax.swing.JMenuItem linkAlugeis;
    private javax.swing.JMenuItem linkClientes;
    private javax.swing.JMenuItem linkPagamentos;
    private javax.swing.JMenuItem linkVeiculos;
    private javax.swing.JMenu menuAgencias;
    private javax.swing.JMenu menuAlugueis;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuClientes;
    private javax.swing.JMenu menuPagamentos;
    private javax.swing.JMenu menuVeiculos;
    private javax.swing.JPanel painelInicial;
    // End of variables declaration//GEN-END:variables
}
